//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaSachFahasa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLNhaSachFahasa.Resources.ViewText", typeof(ViewText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string BUTTON_ADD_TO_CART {
            get {
                return ResourceManager.GetString("BUTTON_ADD_TO_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart confirmation.
        /// </summary>
        public static string BUTTON_CART_CONFIRM {
            get {
                return ResourceManager.GetString("BUTTON_CART_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BUTTON_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BUTTON_SEARCH {
            get {
                return ResourceManager.GetString("BUTTON_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string BUTTON_SUBMIT {
            get {
                return ResourceManager.GetString("BUTTON_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAM.
        /// </summary>
        public static string DV_GAM {
            get {
                return ResourceManager.GetString("DV_GAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string DV_SO_TRANG {
            get {
                return ResourceManager.GetString("DV_SO_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00x00x00.
        /// </summary>
        public static string EXAM_KICH_THUOC {
            get {
                return ResourceManager.GetString("EXAM_KICH_THUOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string LABLE_HELLO {
            get {
                return ResourceManager.GetString("LABLE_HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LABLE_LOGIN {
            get {
                return ResourceManager.GetString("LABLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string LABLE_OR {
            get {
                return ResourceManager.GetString("LABLE_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LABLE_REGISTER {
            get {
                return ResourceManager.GetString("LABLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string LABLE_SEARCH {
            get {
                return ResourceManager.GetString("LABLE_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information.
        /// </summary>
        public static string LINK_UPDATE_INFO {
            get {
                return ResourceManager.GetString("LINK_UPDATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format .jpeg, .jpg, .png. File size max 5MB. .
        /// </summary>
        public static string NOTE_UPLOAD_FILE_IMAGE {
            get {
                return ResourceManager.GetString("NOTE_UPLOAD_FILE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included VAT (if any).
        /// </summary>
        public static string NOTE_VAT {
            get {
                return ResourceManager.GetString("NOTE_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +84 353 033 933.
        /// </summary>
        public static string PHONE_CONTACT {
            get {
                return ResourceManager.GetString("PHONE_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ.
        /// </summary>
        public static string PLACEHOLDER_INPUT_ADDRESS {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string PLACEHOLDER_INPUT_COMFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_COMFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ email.
        /// </summary>
        public static string PLACEHOLDER_INPUT_EMAIL {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại.
        /// </summary>
        public static string PLACEHOLDER_INPUT_MOBILE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ và tên.
        /// </summary>
        public static string PLACEHOLDER_INPUT_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu.
        /// </summary>
        public static string PLACEHOLDER_INPUT_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên đăng nhập.
        /// </summary>
        public static string PLACEHOLDER_INPUT_USERNAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string PLACEHOLDER_USERNAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t stop giving love even if you don’t receive it! Smile and have patience!.
        /// </summary>
        public static string RANDOM_TEXT_0 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All work and no play makes Jack a dull boy..
        /// </summary>
        public static string RANDOM_TEXT_1 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A great lover is not one who loves many, but one who loves one woman for life..
        /// </summary>
        public static string RANDOM_TEXT_2 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendship often ends in love, but love in friendship – never..
        /// </summary>
        public static string RANDOM_TEXT_3 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clean fast is better than a dirty breakfast..
        /// </summary>
        public static string RANDOM_TEXT_4 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calamity is man’s true touchstone..
        /// </summary>
        public static string RANDOM_TEXT_5 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me who your friends are and I’ll tell you who you are.
        /// </summary>
        public static string RANDOM_TEXT_6 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string TEXT_NO_DATA_FOUND {
            get {
                return ResourceManager.GetString("TEXT_NO_DATA_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối truy cập. Liên hệ với ban quản trị để được hỗ trợ..
        /// </summary>
        public static string TEXT_PAGE_ERROR {
            get {
                return ResourceManager.GetString("TEXT_PAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhân viên.
        /// </summary>
        public static string TITLE_ADD_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_ADD_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TITLE_ADDRESS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string TITLE_ALL {
            get {
                return ResourceManager.GetString("TITLE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string TITLE_BOOK {
            get {
                return ResourceManager.GetString("TITLE_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string TITLE_CART {
            get {
                return ResourceManager.GetString("TITLE_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string TITLE_CHUC_DANH {
            get {
                return ResourceManager.GetString("TITLE_CHUC_DANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh nhân dân.
        /// </summary>
        public static string TITLE_CMND {
            get {
                return ResourceManager.GetString("TITLE_CMND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string TITLE_CONFIM_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CONFIM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string TITLE_CONTACT {
            get {
                return ResourceManager.GetString("TITLE_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới sách.
        /// </summary>
        public static string TITLE_CREATE_BOOK {
            get {
                return ResourceManager.GetString("TITLE_CREATE_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string TITLE_CREATE_DATE {
            get {
                return ResourceManager.GetString("TITLE_CREATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string TITLE_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found.
        /// </summary>
        public static string TITLE_DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("TITLE_DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string TITLE_DATEOFBIRTH {
            get {
                return ResourceManager.GetString("TITLE_DATEOFBIRTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery charges.
        /// </summary>
        public static string TITLE_DELIVERY_CHARGES {
            get {
                return ResourceManager.GetString("TITLE_DELIVERY_CHARGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TITLE_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string TITLE_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi 401.
        /// </summary>
        public static string TITLE_ERROR {
            get {
                return ResourceManager.GetString("TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookstore online.
        /// </summary>
        public static string TITLE_FAHASA {
            get {
                return ResourceManager.GetString("TITLE_FAHASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Support 24/7.
        /// </summary>
        public static string TITLE_FREE_SUPPORT {
            get {
                return ResourceManager.GetString("TITLE_FREE_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá sách.
        /// </summary>
        public static string TITLE_GIA_SACH {
            get {
                return ResourceManager.GetString("TITLE_GIA_SACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức.
        /// </summary>
        public static string TITLE_HINH_THUC {
            get {
                return ResourceManager.GetString("TITLE_HINH_THUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string TITLE_HO {
            get {
                return ResourceManager.GetString("TITLE_HO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string TITLE_HOME {
            get {
                return ResourceManager.GetString("TITLE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string TITLE_ID {
            get {
                return ResourceManager.GetString("TITLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sách.
        /// </summary>
        public static string TITLE_ID_BOOK {
            get {
                return ResourceManager.GetString("TITLE_ID_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string TITLE_ID_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_ID_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string TITLE_IMAGE {
            get {
                return ResourceManager.GetString("TITLE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin sách.
        /// </summary>
        public static string TITLE_INFO_BOOK {
            get {
                return ResourceManager.GetString("TITLE_INFO_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string TITLE_INFO_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_INFO_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhân viên.
        /// </summary>
        public static string TITLE_INFO_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_INFO_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Information.
        /// </summary>
        public static string TITLE_INFO_ORDER {
            get {
                return ResourceManager.GetString("TITLE_INFO_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        public static string TITLE_KICH_THUOC {
            get {
                return ResourceManager.GetString("TITLE_KICH_THUOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string TITLE_LAST_NAME {
            get {
                return ResourceManager.GetString("TITLE_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sách.
        /// </summary>
        public static string TITLE_LIST_BOOK {
            get {
                return ResourceManager.GetString("TITLE_LIST_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách khách hàng.
        /// </summary>
        public static string TITLE_LIST_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_LIST_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string TITLE_LIST_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_LIST_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string TITLE_LOGOUT {
            get {
                return ResourceManager.GetString("TITLE_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TITLE_NAME {
            get {
                return ResourceManager.GetString("TITLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sách .
        /// </summary>
        public static string TITLE_NAME_BOOK {
            get {
                return ResourceManager.GetString("TITLE_NAME_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string TITLE_NAME_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_NAME_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string TITLE_NGON_NGU {
            get {
                return ResourceManager.GetString("TITLE_NGON_NGU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà xuất bản.
        /// </summary>
        public static string TITLE_NHA_XUAT_BAN {
            get {
                return ResourceManager.GetString("TITLE_NHA_XUAT_BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string TITLE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại.
        /// </summary>
        public static string TITLE_PHAN_LOAI {
            get {
                return ResourceManager.GetString("TITLE_PHAN_LOAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân Quyền Truy Cập.
        /// </summary>
        public static string TITLE_PHAN_QUYEN {
            get {
                return ResourceManager.GetString("TITLE_PHAN_QUYEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string TITLE_PHONE {
            get {
                return ResourceManager.GetString("TITLE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường/Xã.
        /// </summary>
        public static string TITLE_PHUONG {
            get {
                return ResourceManager.GetString("TITLE_PHUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional.
        /// </summary>
        public static string TITLE_PROVISIONAL {
            get {
                return ResourceManager.GetString("TITLE_PROVISIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string TITLE_QUAN {
            get {
                return ResourceManager.GetString("TITLE_QUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        public static string TITLE_QUOC_GIA {
            get {
                return ResourceManager.GetString("TITLE_QUOC_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền truy cập.
        /// </summary>
        public static string TITLE_QUYEN_TRUY_CAP {
            get {
                return ResourceManager.GetString("TITLE_QUYEN_TRUY_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string TITLE_REGISTER {
            get {
                return ResourceManager.GetString("TITLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        public static string TITLE_SEE_ALL {
            get {
                return ResourceManager.GetString("TITLE_SEE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang.
        /// </summary>
        public static string TITLE_SO_TRANG {
            get {
                return ResourceManager.GetString("TITLE_SO_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationerry.
        /// </summary>
        public static string TITLE_STATIONERY {
            get {
                return ResourceManager.GetString("TITLE_STATIONERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TITLE_STATUS {
            get {
                return ResourceManager.GetString("TITLE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TITLE_TEN {
            get {
                return ResourceManager.GetString("TITLE_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/Thành phố.
        /// </summary>
        public static string TITLE_THANH_PHO {
            get {
                return ResourceManager.GetString("TITLE_THANH_PHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắc.
        /// </summary>
        public static string TITLE_TOM_TAC {
            get {
                return ResourceManager.GetString("TITLE_TOM_TAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TITLE_TOTAL {
            get {
                return ResourceManager.GetString("TITLE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng.
        /// </summary>
        public static string TITLE_TRONG_LUONG {
            get {
                return ResourceManager.GetString("TITLE_TRONG_LUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update order information.
        /// </summary>
        public static string TITLE_UPDATE_INFO_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_INFO_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string TITLE_USERNAME {
            get {
                return ResourceManager.GetString("TITLE_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string TITLE_VIEW {
            get {
                return ResourceManager.GetString("TITLE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        public static string TITTLE_TAC_GIA {
            get {
                return ResourceManager.GetString("TITTLE_TAC_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string TXT_CHOOSE_STATUS {
            get {
                return ResourceManager.GetString("TXT_CHOOSE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₫.
        /// </summary>
        public static string VND {
            get {
                return ResourceManager.GetString("VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the FAHASA Family.
        /// </summary>
        public static string WELCOME_FAHASA {
            get {
                return ResourceManager.GetString("WELCOME_FAHASA", resourceCulture);
            }
        }
    }
}
